src/app/components/NewTokenAmountPanel/NewTokenAmountPanel.d.ts
src/app/components/NewTokenAmountPanel/NewTokenAmountPanel.tsx
src/app/pages/Swap/components/Panels/SwapPanel.tsx
src/utils/data/covalent.ts
src/utils/data/formatters.ts
src/utils/data/inspirit.ts

- Adding fallback to balances on swap page
- Using trade data from paraswap as fallback for usd input value

Adding fallback to balances and usd values on amount panel

---

src/app/layouts/TopBar/TopBar.tsx
src/app/layouts/TopBar/__tests__/__snapshots__/TopBar.test.tsx.snap
src/app/layouts/TopBar/components/TokenInfoBar/TokenInfoBar.tsx
src/app/layouts/TopBar/components/TokenInfoBar/styles.ts
src/theme/chakra/components/button.ts

- Added Spirit price and sorted the stats on the top bar

Topbarinfo

---

src/app/pages/Farms/Farms.tsx
src/app/pages/Inspirit/components/Voting/components/TokenTableV3/TokenTableV3.tsx
src/app/utils/methods.ts

fixed toggle only user farms

---

src/app/pages/SpiritWars/SpiritWars.tsx
src/app/pages/SpiritWars/spiritWarsHelpers.ts
src/workers/dataWorker.ts

- Fix duplicated fileds on spiritwars page

Fixing spiritwars page

---

src/app/hooks/usePieChartData.ts
src/app/pages/Inspirit/components/Voting/components/VotingPanel/VotingPanel.tsx

- Fixed the black colors when u switch from user Farms to all farms

fixed pie black color

---

src/constants/index.ts

- Covalent api changed to one below spirit org domain

Covalent api key changed

---

src/app/hooks/useGetGasPrice.ts

multiply by two

---

src/app/layouts/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/app/pages/Farms/components/FarmTransaction/FarmTransaction.tsx
src/app/pages/Liquidity/components/Collapse/Collapse.tsx
src/utils/data/balances.ts
src/utils/data/spiritwars.ts
src/workers/dataWorker.ts

- Fixed issues with MAI name and logo on Lps

Main to Production

---

src/app/components/PageFooter/PageFooter.tsx
src/app/layouts/Footer/Footer.tsx

Telegram link changed

---

src/app/hooks/useGetGasPrice.ts

new API implemented

---

README.md
src/app/components/TokenSelection/TokenSelection.tsx
src/app/pages/Swap/Swap.tsx

added steps to load images

---

src/app/hooks/useGetGasPrice.ts
src/app/pages/Swap/components/Confirm/SwapConfirm.tsx
src/utils/web3/actions/swap.ts

- New set up for gas price stuff.
- standar speed will use the metamask gas price
- the rest speeds will use the gas price from api

fixing gas price with new set up

---

src/app/pages/Farms/Farm/Farm.tsx
src/app/pages/Farms/components/BoostFactor/BoostFactor.tsx
src/app/pages/Farms/components/BoostFactor/styles.ts
src/app/pages/Farms/components/YourApr/YourApr.d.ts
src/app/pages/Farms/components/YourApr/YourApr.tsx
src/app/pages/Farms/components/YourApr/styles.ts
src/locales/en/translation.json
src/theme/chakra/theme.ts

- Updating boosted section on farms

adding new boosted farm section

---

README.md

- Updated Readme whitelist token

updated steps

---

src/app/components/ModalToken/__tests__/__snapshots__/ModalToken.test.tsx.snap

Snapshots updated on main

---

src/app/components/ModalToken/__tests__/__snapshots__/ModalToken.test.tsx.snap
src/app/pages/Inspirit/components/Aside/components/GetInSpirit/GetInSpirit.tsx

- Fixing issue regarding balances on locking more spirit in inspirit page

fixed issue on inspirit with balances

---

src/app/layouts/Footer/Footer.d.ts
src/app/layouts/Footer/Footer.tsx
src/app/layouts/Footer/__tests__/__snapshots__/Footer.test.tsx.snap

- Fixing tabs on mobile now it will be selected based on the pathname.

Fix: Footer tabs on mobile

---

src/app/components/ModalToken/__tests__/__snapshots__/ModalToken.test.tsx.snap

fix snapshots

---

src/app/pages/Liquidity/Liquidity.tsx
src/constants/networks.ts
src/utils/web3/actions/general.ts
src/utils/web3/actions/swap.ts
src/utils/web3/connection.ts

- Added new RPCS from Fantom (publics ones)
- Called differents providers on differentes sections from Spiritswap

divided RPCs calls from differents providers

---

src/constants/index.ts
src/constants/tokens.ts
src/utils/swap/paraswap.ts
src/utils/web3/actions/swap.ts

fixing JEFE and rainSPIRIR token params on swap

---

src/app/components/ModalToken/__tests__/__snapshots__/ModalToken.test.tsx.snap

snapshots updated

---

src/app/pages/Inspirit/components/Voting/components/MobileRow/MobileRow.tsx
src/app/pages/Inspirit/components/Voting/components/MobileTable/MobileTable.d.ts
src/app/pages/Inspirit/components/Voting/components/MobileTable/MobileTable.tsx
src/app/pages/Inspirit/components/Voting/components/TokenTableV3/HeaderTable.tsx
src/app/pages/Inspirit/components/Voting/components/TokenTableV3/TokenTableV3.tsx
src/app/pages/Inspirit/components/Voting/components/VotingPanel/VotingPanel.tsx

added single row and select farm

---

src/app/components/ModalToken/__tests__/__snapshots__/ModalToken.test.tsx.snap
src/app/pages/Inspirit/components/Voting/components/MobileRow/MobileRow.tsx
src/app/pages/Inspirit/components/Voting/components/MobileTable/MobileTable.d.ts
src/app/pages/Inspirit/components/Voting/components/MobileTable/MobileTable.tsx
src/app/pages/Inspirit/components/Voting/components/TokenTableV3/HeaderTable.tsx
src/app/pages/Inspirit/components/Voting/components/TokenTableV3/TokenTableV3.tsx
src/app/pages/Inspirit/components/Voting/components/VotingPanel/VotingPanel.tsx
src/constants/tokens.ts
src/utils/data/formatters.ts

- Changed name from old DEI name 
- Added new DEI contract

added new dei contract

---

src/constants/networks.ts

put ankr as default

---

src/app/hooks/useLiFi.ts
src/constants/index.ts

Removed connext and avalanche
Added stargate, across and amarok

added new bridges and removed old ones

---

src/app/connectors/EthersConnector/index.tsx
src/app/connectors/EthersConnector/login.ts
src/app/hooks/useGetGasPrice.ts
src/app/index.tsx
src/app/layouts/TopBar/TopBar.tsx
src/app/pages/Home/Home.tsx
src/app/pages/Liquidity/Liquidity.tsx
src/app/router/SiteRouting.tsx
src/constants/index.ts
src/constants/networks.ts
src/contexts/DataContext.tsx
src/utils/web3/actions/general.ts
src/utils/web3/actions/swap.ts
src/utils/web3/connection.ts
src/utils/web3/contracts.ts
src/workers/dataWorker.ts

Fix: RPC calls load balancer

---

src/app/hooks/useLiFi.ts
src/app/pages/Inspirit/components/Voting/components/MobileRow/MobileRow.tsx
src/app/pages/Inspirit/components/Voting/components/MobileTable/MobileTable.tsx
src/constants/errors.ts
src/constants/networks.ts
src/locales/en/translation.json

- Changed Grid to Flex on mobile Inspirit table and row
- Removed Avalanche from bridge Tokens
- Added a new error message on ethereum network

added fixes bridge and mobile

---

src/app/pages/Farms/helpers/filters.ts
src/utils/data/pools.ts

Hidden SCARAB + GSCARAB farm to inactive farms list

---

src/app/connectors/EthersConnector/index.tsx
src/app/pages/Home/components/Portfolio.tsx
src/app/router/SiteRouting.tsx
src/constants/index.ts
src/utils/data/pools.ts
src/utils/web3/contracts.ts
src/workers/userDataWorker.ts

- Chart on portfolio hidden
- fix footer

Fix: Footer and hidden chart on portfolio

---

src/app/components/TransactionFlow/TransactionFlow.tsx
src/app/components/TransactionFlowV2/ContentModal/index.tsx
src/app/components/TransactionFlowV2/Step/index.tsx
src/app/components/TransactionFlowV2/TransactionFlowV2.tsx
src/app/pages/Inspirit/components/Aside/components/GetInSpirit/GetInSpirit.d.ts
src/app/pages/Inspirit/components/Aside/components/GetInSpirit/GetInSpirit.tsx
src/constants/index.ts
src/constants/networks.ts
src/utils/web3/connection.ts

- Fix: Select period on inspirit page

Fix: Inspirit page

---

src/app/components/PageFooter/PageFooter.tsx

footer-fix

---

src/app/pages/Farms/Farms.tsx
src/app/pages/Farms/helpers/sortFarms.ts
src/app/pages/Inspirit/components/Aside/components/GetInSpirit/GetInSpirit.tsx
src/app/pages/Inspirit/components/Dashboard/index.tsx
src/app/pages/Inspirit/components/Voting/hooks/useClaimBribes.ts
src/app/pages/Portfolio/components/inSpiritPanel/components/Footer.tsx
src/utils/data/inspirit.ts
src/utils/web3/actions/inspirit.ts

- Fix: Farms sort by emissions

Fix: Farms sort by emissions

---

src/app/components/TransactionFlow/utils/helper.ts
src/app/pages/Farms/Farms.tsx
src/app/pages/Farms/components/FarmControls/FarmControls.tsx
src/app/pages/Farms/helpers/sortFarms.ts
src/app/pages/Inspirit/components/Aside/components/GetInSpirit/GetInSpirit.tsx
src/app/pages/Inspirit/components/Dashboard/index.tsx
src/app/pages/Inspirit/components/Voting/hooks/useClaimBribes.ts
src/app/pages/Portfolio/components/LimitOrderPanelV2/LimitOrdersPanelV2.tsx
src/app/pages/Portfolio/components/inSpiritPanel/components/Footer.tsx
src/constants/index.ts
src/utils/data/inspirit.ts
src/utils/web3/actions/inspirit.ts

- Fixing claim rewards on inspirit page.

Fix: Claim rewards flow

---

src/app/components/TWAP/TWAPOrders.tsx
src/app/pages/Swap/Swap.tsx
src/app/pages/Swap/components/Chart/Chart.tsx
src/app/pages/Swap/components/Chart/styles.ts
src/app/pages/Swap/components/LimitOrders/styles.ts
src/app/pages/Swap/styles.ts
src/app/utils/methods.ts

Feat: New chart insted

---

src/app/pages/Inspirit/components/Voting/components/VotingPanel/VotingPanel.tsx
src/constants/farms/index.ts
src/utils/data/pools.ts

- Added toUpperCase
- Uopdated list

removed farms

---

package.json
src/app/connectors/EthersConnector/index.tsx
src/app/hooks/useTokenBalance.ts
src/types/index.ts
src/utils/data/balances.ts
src/utils/data/inspirit.ts
src/utils/data/pools.ts
src/utils/web3/actions/lendandborrow.ts
src/utils/web3/connection.ts
src/utils/web3/contracts.ts
src/workers/dataWorker.ts
src/workers/userDataWorker.ts

- Reduce the number of calls made by 75% by utilizing a more advanced Multicall function
- Reduce duplicate calls to functions when not necessary

Fix high calls issues

---

src/utils/web3/actions/lendandborrow.ts
src/utils/web3/contracts.ts

Fix: Handling undefined values
